export const OPEN_LOADING = "OPEN_LOADING";
export const CLOSE_LOADING = "CLOSE_LOADING";

export const TOGGLE_DRAWER = "TOGGLE_DRAWER";

export const SET_USER_DETAIL = "SET_USER_DETAIL";

export const GET_ALL_USER = "GET_ALL_USER";
export const GET_ALL_USER_SUCCESS = "GET_ALL_USER_SUCCESS";
export const GET_ALL_USER_FAIL = "GET_ALL_USER_FAIL";

export const FILTER_USER = "FILTER_USER";
export const FILTER_USER_SUCCESS = "FILTER_USER_SUCCESS";
export const FILTER_USER_FAIL = "FILTER_USER_FAIL";

export const GET_MORE_USER = "GET_MORE_USER";
export const GET_MORE_USER_SUCCESS = "GET_MORE_USER_SUCCESS";
export const GET_MORE_USER_FAIL = "GET_MORE_USER_FAIL";

export const ADD_USER = "ADD_USER";
export const ADD_USER_SUCCESS = "ADD_USER_SUCCESS";
export const ADD_USER_FAIL = "ADD_REQUEST_FAIL";

export const UPDATE_USER = "UPDATE_USER";
export const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS";
export const UPDATE_USER_FAIL = "UPDATE_USER_FAIL";

export const DELETE_USER = "DELETE_USER";
export const DELETE_USER_SUCCESS = "DELETE_USER_SUCCESS";
export const DELETE_USER_FAIL = "DELETE_USER_FAIL";

export const LOGOUT = "LOGOUT";

export const LOGIN = "LOGIN";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";

export const GET_MY_PROFILE = "GET_MY_PROFILE";
export const GET_MY_PROFILE_SUCCESS = "GET_MY_PROFILE_SUCCESS";
export const GET_MY_PROFILE_FAIL = "GET_MY_PROFILE_FAIL";

export const REGISTER_GOOGLE = "REGISTER_GOOGLE";
export const REGISTER_GOOGLE_SUCCESS = "REGISTER_GOOGLE_SUCCESS";
export const REGISTER_GOOGLE_FAIL = "REGISTER_GOOGLE_FAIL";

export const LOGIN_GOOGLE = "LOGIN_GOOGLE";
export const LOGIN_GOOGLE_SUCCESS = "LOGIN_GOOGLE_SUCCESS";
export const LOGIN_GOOGLE_FAIL = "LOGIN_GOOGLE_FAIL";

export const TO_REQUEST_DETAIL = "TO_REQUEST_DETAIL";

export const ADD_REQUEST = "ADD_REQUEST";
export const ADD_REQUEST_SUCCESS = "ADD_REQUEST_SUCCESS";
export const ADD_REQUEST_FAIL = "ADD_REQUEST_FAIL";

export const GET_REQUEST = "GET_REQUEST";
export const GET_REQUEST_SUCCESS = "GET_REQUEST_SUCCESS";
export const GET_REQUEST_FAIL = "GET_REQUEST_FAIL";

export const FETCH_ASSIGN = "FETCH_ASSIGN";
export const FETCH_ASSIGN_SUCCESS = "FETCH_ASSIGN_SUCCESS";
export const FETCH_ASSIGN_FAILED = "FETCH_ASSIGN_FAILED";

export const FETCH_REQUEST_DETAIL = "FETCH_REQUEST_DETAIL";
export const FETCH_REQUEST_DETAIL_SUCCESS = "FETCH_REQUEST_DETAIL_SUCCESS";

export const FETCH_COMMENT = "FETCH_COMMENT";
export const FETCH_COMMENT_SUCCESS = "FETCH_COMMENT_SUCCESS";
export const FETCH_COMMENT_FAILED = "FETCH_COMMENT_FAILED";

export const POST_COMMENT = "POST_COMMENT";
export const POST_COMMENT_SUCCESS = "POST_COMMENT_SUCCESS";
export const POST_COMMENT_FAILED = "POST_COMMENT_FAILED";
export const REFRESH_COMMENT = "REFRESH_COMMENT";

export const FETCH_CATEGORY = "FETCH_CATEGORY";
export const FETCH_CATEGORY_SUCCESS = "FETCH_CATEGORY_SUCCESS";
export const FETCH_CATEGORY_FAILED = "FETCH_CATEGORY_FAILED";

export const FILTER_CATEGORY = "FILTER_CATEGORY";
export const FILTER_CATEGORY_SUCCESS = "FILTER_CATEGORY_SUCCESS";
export const FILTER_CATEGORY_FAIL = "FILTER_CATEGORY_FAIL";

export const ADD_CATEGORY = "ADD_CATEGORY";
export const ADD_CATEGORY_SUCCESS = "ADD_CATEGORY_SUCCESS";
export const ADD_CATEGORY_FAIL = "ADD_CATEGORY_FAIL";

export const UPDATE_CATEGORY = "UPDATE_CATEGORY";
export const UPDATE_CATEGORY_SUCCESS = "UPDATE_CATEGORY_SUCCESS";
export const UPDATE_CATEGORY_FAIL = "UPDATE_CATEGORY_FAIL";

export const FETCH_ALL_CATEGORY = "FETCH_ALL_CATEGORY";
export const FETCH_ALL_CATEGORY_SUCCESS = "FETCH_ALL_CATEGORY_SUCCESS";
export const FETCH_ALL_CATEGORY_FAIL = "FETCH_ALL_CATEGORY_FAIL";

export const FETCH_ALL_ASSIGNEE = "FETCH_ALL_ASSIGNEE";
export const FETCH_ALL_ASSIGNEE_SUCCESS = "FETCH_ALL_ASSIGNEE_SUCCESS";
export const FETCH_ALL_ASSIGNEE_FAIL = "FETCH_ALL_ASSIGNEE_FAIL";

export const UPDATE_REQUEST = "UPDATE_REQUEST";
export const UPDATE_REQUEST_SUCCESS = "UPDATE_REQUEST_SUCCESS";
export const UPDATE_REQUEST_FAILED = "UPDATE_REQUEST_FAILED";

export const GET_DEPARTMENT = "GET_DEPARTMENT";
export const GET_DEPARTMENT_SUCCESS = "GET_DEPARTMENT_SUCCESS";
export const GET_DEPARTMENT_FAIL = "GET_DEPARTMENT_FAIL";

export const FETCH_DEPARTMENT = "FETCH_DEPARTMENT";
export const FETCH_DEPARTMENT_SUCCESS = "FETCH_DEPARTMENT_SUCCESS";
export const FETCH_DEPARTMENT_FAILED = "FETCH_DEPARTMENT_FAILED";

export const FILTER_DEPARTMENT = "FILTER_DEPARTMENT";
export const FILTER_DEPARTMENT_SUCCESS = "FILTER_DEPARTMENT_SUCCESS";
export const GET_LIST_HISTORY_REQUEST = "GET_LIST_HISTORY_REQUEST";
export const GET_LIST_HISTORY_REQUEST_SUCCESS =
  "GET_LIST_HISTORY_REQUEST_SUCCESS";
export const GET_LIST_HISTORY_REQUEST_FAIL = "GET_LIST_HISTORY_REQUEST_FAIL";

export const CREATE_DEPARTMENT = "CREATE_DEPARTMENT";
export const EDIT_DEPARTMENT = "EDIT_DEPARTMENT";

export const DELETE_REQUEST = "DELETE_REQUEST";
